# Generated by Django 4.0.1 on 2023-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OrganizationId', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.URLField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Founded', models.CharField(blank=True, max_length=50, null=True)),
                ('Industry', models.CharField(blank=True, max_length=50, null=True)),
                ('Numberofemployees', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': True,
            },
        ),
    ]
