# Generated by Django 4.0.1 on 2023-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
