# Generated by Django 4.0.1 on 2023-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycsv', '0002_company_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='upload_at',
            field=models.DateTimeField(),
        ),
    ]
